
dbItems = {
	[771] = {
		["info"] = {
			["itemName"] = "Chipped Boar Tusk",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemIcon"] = 133721,
			["bindType"] = 0,
			["itemRarity"] = 0,
			["itemMinLevel"] = 0,
			["itemType"] = "Miscellaneous",
			["itemSellPrice"] = 38,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Junk",
			["itemLink"] = "|cff9d9d9d|Hitem:771::::::::1:71::::::|h[Chipped Boar Tusk]|h|r",
			["itemClassID"] = 15,
		},
		["stats"] = {
		},
	},
	[55973] = {
		["info"] = {
			["itemName"] = "Inert Elemental Speck",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemClassID"] = 15,
			["bindType"] = 0,
			["itemRarity"] = 0,
			["itemMinLevel"] = 0,
			["itemType"] = "Miscellaneous",
			["itemSellPrice"] = 1,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Junk",
			["itemLink"] = "|cff9d9d9d|Hitem:55973::::::::1:71::::::|h[Inert Elemental Speck]|h|r",
			["itemIcon"] = 132872,
		},
		["stats"] = {
		},
	},
	["16114"] = {
		["info"] = {
			["itemName"] = "Foreman's Blackjack",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 1,
			["itemClassID"] = 12,
			["bindType"] = 4,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Quest",
			["itemSellPrice"] = 0,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Quest",
			["itemLink"] = "|cffffffff|Hitem:16114::::::::3:71::11::::|h[Foreman's Blackjack]|h|r",
			["itemIcon"] = 133486,
		},
		["stats"] = {
		},
	},
	["117"] = {
		["info"] = {
			["itemName"] = "Tough Jerky",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemIcon"] = 133972,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 1,
			["itemType"] = "Consumable",
			["itemSellPrice"] = 1,
			["itemSubClassID"] = 5,
			["itemSubType"] = "Food & Drink",
			["itemLink"] = "|cffffffff|Hitem:117::::::::3:71::::::|h[Tough Jerky]|h|r",
			["itemClassID"] = 0,
		},
		["stats"] = {
		},
	},
	[2592] = {
		["info"] = {
			["itemName"] = "Wool Cloth",
			["itemLevel"] = 15,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 200,
			["itemIcon"] = 132911,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Tradeskill",
			["itemSellPrice"] = 33,
			["itemSubClassID"] = 5,
			["itemSubType"] = "Cloth",
			["itemLink"] = "|cffffffff|Hitem:2592::::::::20:261::::::|h[Wool Cloth]|h|r",
			["itemClassID"] = 7,
		},
		["stats"] = {
		},
	},
	["4862"] = {
		["info"] = {
			["itemName"] = "Scorpid Worker Tail",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemIcon"] = 132274,
			["bindType"] = 4,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Quest",
			["itemSellPrice"] = 0,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Quest",
			["itemLink"] = "|cffffffff|Hitem:4862::::::::3:71::::::|h[Scorpid Worker Tail]|h|r",
			["itemClassID"] = 12,
		},
		["stats"] = {
		},
	},
	["53373"] = {
		["info"] = {
			["itemName"] = "Hearth Defender Bracers",
			["itemLevel"] = 3,
			["itemEqupLoc"] = "INVTYPE_WRIST",
			["itemStackCount"] = 1,
			["itemIcon"] = 443339,
			["bindType"] = 1,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Armor",
			["itemSellPrice"] = 4,
			["itemSubClassID"] = 4,
			["itemSubType"] = "Plate",
			["itemLink"] = "|cffffffff|Hitem:53373::::::::2:71::11::::|h[Hearth Defender Bracers]|h|r",
			["itemClassID"] = 4,
		},
		["stats"] = {
			["RESISTANCE0_NAME"] = 3,
		},
	},
	["2132"] = {
		["info"] = {
			["itemName"] = "Short Staff",
			["itemLevel"] = 4,
			["itemEqupLoc"] = "INVTYPE_2HWEAPON",
			["itemStackCount"] = 1,
			["itemClassID"] = 2,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 1,
			["itemType"] = "Weapon",
			["itemSellPrice"] = 20,
			["itemSubClassID"] = 10,
			["itemSubType"] = "Staves",
			["itemLink"] = "|cffffffff|Hitem:2132::::::::2:71::14::::|h[Short Staff]|h|r",
			["itemIcon"] = 135139,
		},
		["stats"] = {
			["ITEM_MOD_DAMAGE_PER_SECOND_SHORT"] = 0.6944444179534912,
		},
	},
	["4496"] = {
		["info"] = {
			["itemName"] = "Small Brown Pouch",
			["itemLevel"] = 5,
			["itemEqupLoc"] = "INVTYPE_BAG",
			["itemStackCount"] = 1,
			["itemClassID"] = 1,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Container",
			["itemSellPrice"] = 125,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Bag",
			["itemLink"] = "|cffffffff|Hitem:4496::::::::2:71::::::|h[Small Brown Pouch]|h|r",
			["itemIcon"] = 133634,
		},
		["stats"] = {
		},
	},
	[55983] = {
		["info"] = {
			["itemName"] = "Inert Elemental Scintilla",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemClassID"] = 15,
			["bindType"] = 0,
			["itemRarity"] = 0,
			["itemMinLevel"] = 0,
			["itemType"] = "Miscellaneous",
			["itemSellPrice"] = 7,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Junk",
			["itemLink"] = "|cff9d9d9d|Hitem:55983::::::::1:71::::::|h[Inert Elemental Scintilla]|h|r",
			["itemIcon"] = 132872,
		},
		["stats"] = {
		},
	},
	["6948"] = {
		["info"] = {
			["itemName"] = "Hearthstone",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 1,
			["itemIcon"] = 134414,
			["bindType"] = 1,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Miscellaneous",
			["itemSellPrice"] = 0,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Junk",
			["itemLink"] = "|cffffffff|Hitem:6948::::::::3:71::::::|h[Hearthstone]|h|r",
			["itemClassID"] = 15,
		},
		["stats"] = {
		},
	},
	["56968"] = {
		["info"] = {
			["itemName"] = "Bug Juice",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemType"] = "Miscellaneous",
			["bindType"] = 0,
			["itemRarity"] = 0,
			["itemMinLevel"] = 0,
			["itemClassID"] = 15,
			["itemSellPrice"] = 1,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Junk",
			["itemLink"] = "|cff9d9d9d|Hitem:56968::::::::3:71::::::|h[Bug Juice]|h|r",
			["itemIcon"] = 134437,
		},
		["stats"] = {
		},
	},
	["771"] = {
		["info"] = {
			["itemName"] = "Chipped Boar Tusk",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemIcon"] = 133721,
			["bindType"] = 0,
			["itemRarity"] = 0,
			["itemMinLevel"] = 0,
			["itemType"] = "Miscellaneous",
			["itemSellPrice"] = 38,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Junk",
			["itemLink"] = "|cff9d9d9d|Hitem:771::::::::3:71::::::|h[Chipped Boar Tusk]|h|r",
			["itemClassID"] = 15,
		},
		["stats"] = {
		},
	},
	[117] = {
		["info"] = {
			["itemName"] = "Tough Jerky",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemIcon"] = 133972,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 1,
			["itemType"] = "Consumable",
			["itemSellPrice"] = 1,
			["itemSubClassID"] = 5,
			["itemSubType"] = "Food & Drink",
			["itemLink"] = "|cffffffff|Hitem:117::::::::2:71::::::|h[Tough Jerky]|h|r",
			["itemClassID"] = 0,
		},
		["stats"] = {
		},
	},
	[2589] = {
		["info"] = {
			["itemName"] = "Linen Cloth",
			["itemLevel"] = 5,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 200,
			["itemClassID"] = 7,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Tradeskill",
			["itemSellPrice"] = 13,
			["itemSubClassID"] = 5,
			["itemSubType"] = "Cloth",
			["itemLink"] = "|cffffffff|Hitem:2589::::::::20:261::::::|h[Linen Cloth]|h|rx3",
			["itemIcon"] = 132889,
		},
		["stats"] = {
		},
	},
	["7099"] = {
		["info"] = {
			["itemName"] = "Severed Pincer",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemIcon"] = 133708,
			["bindType"] = 0,
			["itemRarity"] = 0,
			["itemMinLevel"] = 0,
			["itemType"] = "Miscellaneous",
			["itemSellPrice"] = 6,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Junk",
			["itemLink"] = "|cff9d9d9d|Hitem:7099::::::::3:71::::::|h[Severed Pincer]|h|r",
			["itemClassID"] = 15,
		},
		["stats"] = {
		},
	},
	[53360] = {
		["info"] = {
			["itemName"] = "Bragger's Gauntlets",
			["itemLevel"] = 2,
			["itemEqupLoc"] = "INVTYPE_HAND",
			["itemStackCount"] = 1,
			["itemClassID"] = 4,
			["bindType"] = 1,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Armor",
			["itemSellPrice"] = 2,
			["itemSubClassID"] = 4,
			["itemSubType"] = "Plate",
			["itemLink"] = "|cffffffff|Hitem:53360::::::::2:71::11::::|h[Bragger's Gauntlets]|h|r",
			["itemIcon"] = 443360,
		},
		["stats"] = {
			["RESISTANCE0_NAME"] = 5,
		},
	},
	["1194"] = {
		["info"] = {
			["itemName"] = "Bastard Sword",
			["itemLevel"] = 4,
			["itemEqupLoc"] = "INVTYPE_2HWEAPON",
			["itemStackCount"] = 1,
			["itemIcon"] = 135276,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 1,
			["itemType"] = "Weapon",
			["itemSellPrice"] = 21,
			["itemSubClassID"] = 8,
			["itemSubType"] = "Two-Handed Swords",
			["itemLink"] = "|cffffffff|Hitem:1194::::::::2:71::14::::|h[Bastard Sword]|h|r",
			["itemClassID"] = 2,
		},
		["stats"] = {
			["ITEM_MOD_DAMAGE_PER_SECOND_SHORT"] = 0.8333333134651184,
		},
	},
	["53362"] = {
		["info"] = {
			["itemName"] = "Carapace Boots",
			["itemLevel"] = 3,
			["itemEqupLoc"] = "INVTYPE_FEET",
			["itemStackCount"] = 1,
			["itemType"] = "Armor",
			["bindType"] = 1,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemClassID"] = 4,
			["itemSellPrice"] = 5,
			["itemSubClassID"] = 4,
			["itemSubType"] = "Plate",
			["itemLink"] = "|cffffffff|Hitem:53362::::::::4:71::11::::|h[Carapace Boots]|h|r",
			["itemIcon"] = 443336,
		},
		["stats"] = {
			["RESISTANCE0_NAME"] = 5,
		},
	},
	["4905"] = {
		["info"] = {
			["itemName"] = "Sarkoth's Mangled Claw",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 1,
			["itemType"] = "Quest",
			["bindType"] = 4,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemClassID"] = 12,
			["itemSellPrice"] = 0,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Quest",
			["itemLink"] = "|cffffffff|Hitem:4905::::::::3:71::::::|h[Sarkoth's Mangled Claw]|h|r",
			["itemIcon"] = 134294,
		},
		["stats"] = {
		},
	},
	["11583"] = {
		["info"] = {
			["itemName"] = "Cactus Apple",
			["itemLevel"] = 1,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 10,
			["itemIcon"] = 133975,
			["bindType"] = 4,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Quest",
			["itemSellPrice"] = 0,
			["itemSubClassID"] = 0,
			["itemSubType"] = "Quest",
			["itemLink"] = "|cffffffff|Hitem:11583::::::::2:71::::::|h[Cactus Apple]|h|r",
			["itemClassID"] = 12,
		},
		["stats"] = {
		},
	},
	["53360"] = {
		["info"] = {
			["itemName"] = "Bragger's Gauntlets",
			["itemLevel"] = 2,
			["itemEqupLoc"] = "INVTYPE_HAND",
			["itemStackCount"] = 1,
			["itemClassID"] = 4,
			["bindType"] = 1,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Armor",
			["itemSellPrice"] = 2,
			["itemSubClassID"] = 4,
			["itemSubType"] = "Plate",
			["itemLink"] = "|cffffffff|Hitem:53360::::::::2:71::11::::|h[Bragger's Gauntlets]|h|r",
			["itemIcon"] = 443360,
		},
		["stats"] = {
			["RESISTANCE0_NAME"] = 5,
		},
	},
	["11584"] = {
		["info"] = {
			["itemName"] = "Cactus Apple Surprise",
			["itemLevel"] = 5,
			["itemEqupLoc"] = "",
			["itemStackCount"] = 20,
			["itemIcon"] = 133975,
			["bindType"] = 0,
			["itemRarity"] = 1,
			["itemMinLevel"] = 0,
			["itemType"] = "Consumable",
			["itemSellPrice"] = 1,
			["itemSubClassID"] = 5,
			["itemSubType"] = "Food & Drink",
			["itemLink"] = "|cffffffff|Hitem:11584::::::::3:71::::::|h[Cactus Apple Surprise]|h|r",
			["itemClassID"] = 0,
		},
		["stats"] = {
		},
	},
}
